frettaListi =  [
        {
            "id": 0,
            "flokkur": "almennt",
            "hofundur": "dsg",
            "fyrirsogn": "Flórens veldur usla á Flórída",
            "meginmal": "Það er bara helv... vesen á fellibylnum og allt í klessu í Flórída.  Milljónir manna þurftu að yfirgefa heimili sin vegna yfirvofandi eyðileggingar Flórensar...",
            "mynd": "mynd0.jpg",
        },
        {
            "id": 1,
            "flokkur": "veidi",
            "hofundur": "gjg",
            "fyrirsogn": "Veiðin er dræm þetta haustið",
            "meginmal": "Veiðin hefur heldur verið döpur þetta haustið þrátt fyrir ágætis rigninar upp á síðkastið...",
            "mynd": "mynd1.jpg",
        },
        {
            "id": 2,
            "flokkur": "sport",
            "hofundur": "gus",
            "fyrirsogn": "Ólafía stendur sig vel",
            "meginmal": "Ólafía er komin í 65 sæti peningalistans og hefur því tryggt sér keppnisrétt á LPG mótaröðinni á komandi keppnistimabili...",
            "mynd": "mynd2.jpg",
        },
        {
            "id": 3,
            "flokkur": "sport",
            "hofundur": "gus",
            "fyrirsogn": "Ísland dottið úr leik",
            "meginmal": "Íslenska karlalandsliðið í körfubolta er dottið úr leik a Eurobasket þrátt fyrir ágætis spretti inn a milli.  Ísland spilaði lokaleik sinn á mótinu fyrir troðfullri höll gegn heimamönnum Finnum..",
            "mynd": "mynd3.jpg",
        },
        {
            "id": 4,
            "flokkur": "almennt",
            "hofundur": "dsg",
            "fyrirsogn": "Allt að 21 stigs hiti í dag",
            "meginmal": "Litl­ar breyt­ing­ar verða í veðrinu í dag, sam­kvæmt hug­leiðing­um veður­fræðings Veður­stofu Íslands.Suðvestanátt rík­ir á land­inu, yf­ir­leitt á bil­inu 5-13 m/​s. Víða er létt­skýjað á aust­ur­hluta lands­ins en þung­búið og dá­lít­il rign­ing eða súld með köfl­um sunn­an- og vest­an­til. Hiti verður á bil­inu 11 til 21 stig, hlýj­ast aust­ast á land­inu.Litl­ar breyt­ing­ar verða í veðrinu næstu daga en út­lit er fyr­ir að það dragi úr suðvestanátt­inni í lok vik­unn­ar.",
            "mynd": "mynd4.jpg",
        },
                {
            "id": 5,
            "flokkur": "veidi",
            "hofundur": "gjg",
            "fyrirsogn": "Lifnaði yfir Kjósinni eftir rigningu",
            "meginmal": "Marg­ar ár eru bún­ar að vera afar vatns­litl­ar í sum­ar og eiga inni hvað varðar veiðina. Laxá í Döl­um er til dæm­is þekkt fyr­ir góðan enda­sprett og er þá bund­in við haustrign­ing­ar. Þar hef­ur ekki enn rignt en það er svipað og að spila í lottó­inu að kaupa leyfi í Döl­un­um síðsum­ars eða á haust­dög­um. Þar er hægt að vinna stóra vinn­inga ef menn hitta á rign­ingu sem ger­ir það að verk­um að lax­inn læt­ur sig loks­ins vaða upp í ána og þeir sem eru fyr­ir fá súr­efni.",
            "mynd": "mynd5.jpg",
        }
    ]